# Site settings
title: לפני האיתחול
description: > # this means to ignore newlines until "baseurl:"
  האקינג, קריפטו, ושאר ירקות
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-feed]
paginate: 5 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

url: https://tech.b48.club
enforce_ssl: tech.b48.club
